### ISSUE TITLE
Some problems that can appear. How are they treated ?

### ISSUE THREAD

**Issue by tudor07** [afollestad/udp-discovery#1]
I have some questions regarding some problems that can appear with this library.
How is the discovery done ? Does it send a packet to the broadcast address ?
What if the router blocks by default requests sent to the broadcast address ?
Also I see that the port is hard-coded. What if the port is blocked on a specific device ?
Also I see this is how you get the broadcast address:
int broadcast = (dhcp.ipAddress & dhcp.netmask) | ~dhcp.netmask;
Are you aware of the netmask bug in Android ? Did it happen to you/Did you have any problems with it ? Source: https://code.google.com/p/android/issues/detail?id=82477

Thanks.

**Comment by afollestad** [comment]
I've had no problems with it. This library addresses my specific use case with Raspberry Pi IoT device discovery.
